[pytest]
pythonpath = .
asyncio_mode = auto
filterwarnings =
    error
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::pytest.PytestUnhandledThreadExceptionWarning
    ignore::ResourceWarning
    ignore::DeprecationWarning:discord.*
    ignore::DeprecationWarning:aiohttp.*
    ignore::DeprecationWarning:aiosmtplib.*
    ignore::DeprecationWarning:pkg_resources.*
    ignore::DeprecationWarning:audioop.*
    ignore:.*audioop.*:DeprecationWarning

