[pytest]
pythonpath = .
asyncio_mode = auto
filterwarnings =
    error
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::pytest.PytestUnhandledThreadExceptionWarning
    ignore::ResourceWarning
